postgesql:
  image: postgres:12-alpine

  ports:
    - "5432:5432"
  restart: always
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=auth_db
  volumes:
    - ./pgdata:/var/lib/postgresql/data

